# Generated by Django 3.0.8 on 2020-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20200727_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('CZE', 'Czech'), ('SVK', 'Slovakia'), ('GER', 'Germany'), ('AUS', 'Austria')], default='CZE', max_length=4),
        ),
    ]
