# Generated by Django 3.0.8 on 2020-07-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_auto_20200728_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(default=9989),
        ),
    ]
