# Generated by Django 3.0.8 on 2020-07-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=9999)),
                ('email', models.EmailField(max_length=254)),
                ('account_status', models.PositiveIntegerField(default=1)),
                ('account_created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('times_liked', models.PositiveIntegerField(default=0)),
                ('times_disliked', models.PositiveIntegerField(default=0)),
                ('date_posted', models.DateTimeField(verbose_name='date published')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miblog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(verbose_name='date published')),
                ('times_liked', models.PositiveIntegerField(default=0)),
                ('times_disliked', models.PositiveIntegerField(default=0)),
                ('entry_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miblog.Entry')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miblog.User')),
            ],
        ),
    ]
